import { makeStyles } from "@material-ui/core";

export default makeStyles(() => ({
  header: {
    display: "flex",
    width: "100%",
    justifyContent: "center",
    "& .search": {
      display: "flex",
      flexDirection: "column",
      maxWidth: 600,
      width: "90%",
      position: "absolute",
      top: "30%",
    },
    "& .search.sticky": {
      position: "fixed",
      top: 0,
      background: "#333333",
      width: "100%",
      padding: 12,
      maxWidth: "100%",
      alignItems: "center",
      zIndex: 100,
    },
  },
  stickyDiv: {
    position: "absolute",
    top: "30%",
  },
  list: {
    maxHeight: 200,
    position: "absolute",
    marginTop: 50,
    background: "#fff",
    maxWidth: 600,
    overflow: "scroll",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    boxShadow: "2px 0px 20px -2px rgb(0 0 0 / 75%)",
    padding: 10,
    boxSizing: "border-box",
    borderRadius: 20,
  },
  searchBox: {
    height: 20,
    boxShadow: "2px 0px 20px -2px rgb(0 0 0 / 75%)",
    boxSizing: "border-box",
    padding: 20,
    borderRadius: 20,
    outline: "none",
    border: 0,
    width: "100%",
    maxWidth: 600,
    // background: "#F0F2F5",
  },
  listItem: {
    display: "flex",
    flexDirection: "row",
    fontSize: 10,
    marginBottom: 10,
    width: "100%",
    padding: 10,
    "&:hover": {
      background: "#F3F3F3",
      cursor: "pointer",
    },
  },
  centerText: {
    margin: "0 auto",
  },
  cardTitle: {
    alignSelf: "center",
    textAlign: "left",
    marginLeft: 15,
    fontWeight: 500,
  },
}));
